modLoader="javafml"  # mod加载器,必填
loaderVersion="[47,)"  # mod加载器版本,必填
license="All rights reserved"  # 许可证,必填

[[mods]]  # mod信息,必填
modId="dream_sakura"  # modid,必填
version="0.0.1"  # mod版本,必填
displayName="梦之樱"  # mod显示名称,必填
# logoFile="pack.png"  # mod图标,选填
authors="yueyingiop"  # mod作者,选填
description='''
至此，新序诞生
'''  # mod描述,必填

[[dependencies.dream_sakura]]  # mod依赖,选填
    modId="forge"  # 依赖的modid,必填
    mandatory=true  # 是否必须,必填
    versionRange="[47,)"  # 依赖的版本范围,必填
    ordering="NONE"  # 排序,选填
    side="BOTH"  # 端,选填

[[dependencies.dream_sakura]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.3)"
    ordering="NONE"
    side="BOTH" 

[[dependencies.dream_sakura]]
    modId="curios"
    mandatory=false
    versionRange="[5.12.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dream_sakura]]
    modId="geckolib"
    mandatory=false
    versionRange="[4.7.1,)"
    ordering="NONE"
    side="BOTH"